import './reset.css'
import './globals.css'
import '@/lib/dayjs'
import { ReactNode } from 'react'
import { Roboto_Flex as Roboto } from 'next/font/google'
import { NextAuthProvider } from './providers'

const roboto = Roboto({ subsets: ['latin'], variable: '--font-roboto' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} bg-gray-900 font-sans text-gray-100`}
      >
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
